-- Auto-generated by scripts/bootstrap-db.ts
-- Concatenated migrations from drizzle/ in lexical order.
-- You can apply this with:
--   npx supabase db reset
--   npx supabase db query -f supabase/bootstrap_all.sql

BEGIN;

-- >>> 0001_init.sql >>>
-- Extensions
create extension if not exists pgcrypto;

-- Enums
do $$ begin
  create type system_type as enum ('On-grid', 'Hybrid', 'Off-grid', 'Inverter & Battery', 'Solar Water Heater');
exception when duplicate_object then null; end $$;
do $$ begin
  create type job_status as enum ('Lead', 'Qualified', 'Quoted', 'Won', 'KSEB_Submitted', 'Material_Ordered', 'Installed', 'Net_Metered', 'Handover', 'Closed', 'Lost');
exception when duplicate_object then null; end $$;
do $$ begin
  create type invoice_type as enum ('Deposit', 'Progress', 'Final');
exception when duplicate_object then null; end $$;
do $$ begin
  create type invoice_status as enum ('Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled');
exception when duplicate_object then null; end $$;
do $$ begin
  create type pay_mode as enum ('UPI', 'NEFT', 'Cash', 'Card', 'Cheque');
exception when duplicate_object then null; end $$;
do $$ begin
  create type task_status as enum ('Open', 'InProgress', 'Blocked', 'Done');
exception when duplicate_object then null; end $$;
do $$ begin
  create type priority as enum ('Low', 'Medium', 'High', 'Urgent');
exception when duplicate_object then null; end $$;
do $$ begin
  create type role as enum ('owner', 'staff');
exception when duplicate_object then null; end $$;

-- Tables
create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  user_id uuid primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  role role default 'staff',
  phone text,
  display_name text,
  created_at timestamptz default now(),
  constraint fk_profiles_auth foreign key (user_id) references auth.users(id) on delete cascade
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  phone text,
  email text,
  address text,
  discom text default 'KSEB',
  consumer_no text,
  phase text,
  sanctioned_load_kw numeric(6,2),
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  date date,
  source text,
  name text,
  phone text,
  email text,
  address text,
  interested_capacity_kw numeric(6,2),
  notes text,
  assigned_to uuid,
  status text
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  lead_id uuid references public.leads(id) on delete set null,
  system_type system_type not null,
  capacity_kw numeric(6,2),
  roof_type text,
  status job_status not null default 'Lead',
  quoted_price numeric(12,2),
  discount numeric(12,2),
  tax_rate numeric(5,2),
  total_amount numeric(12,2),
  deposit_amount numeric(12,2),
  balance_due numeric(12,2),
  date_lead date,
  date_site_survey date,
  date_quote date,
  date_won date,
  date_kseb_submit date,
  date_install date,
  date_meter date,
  date_handover date,
  kseb_application_no text,
  subsidy_portal_ref text,
  location text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  date date,
  kit_name text,
  price_before_tax numeric(12,2),
  tax numeric(12,2),
  total numeric(12,2),
  valid_till date,
  pdf_url text,
  terms text
);

create table if not exists public.items (
  item_code text primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  category text,
  unit text,
  gst_rate numeric(5,2),
  mrp numeric(12,2),
  preferred_vendor text,
  specs jsonb
);

create table if not exists public.kits (
  kit_name text primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  description text,
  capacity_kw numeric(6,2),
  selling_price numeric(12,2)
);

create table if not exists public.kit_items (
  kit_name text not null references public.kits(kit_name) on delete cascade,
  item_code text not null references public.items(item_code) on delete cascade,
  qty numeric(10,2),
  primary key (kit_name, item_code)
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  date date,
  invoice_type invoice_type not null,
  amount_before_tax numeric(12,2),
  tax numeric(12,2),
  total numeric(12,2),
  due_date date,
  status invoice_status default 'Draft',
  irn text,
  pdf_url text
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  date date,
  mode pay_mode,
  amount numeric(12,2),
  reference text,
  received_by text,
  notes text
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  doc_type text,
  file_url text,
  version int,
  signed_by text,
  signed_date date,
  notes text
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  title text,
  assigned_to uuid,
  due_date date,
  status task_status default 'Open',
  priority priority default 'Medium',
  notes text
);

create table if not exists public.service_tickets (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  date date,
  issue_type text,
  priority priority default 'Medium',
  status task_status default 'Open',
  summary text,
  assigned_to uuid,
  resolution_notes text
);

create table if not exists public.background_jobs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  type text not null,
  payload jsonb,
  run_at timestamptz default now(),
  attempts int default 0,
  last_error text
);

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  currency text default 'INR',
  upi_id text,
  default_tax_rate numeric(5,2) default 0,
  primary_discom text default 'KSEB',
  proposal_note_ml text,
  deposit_percent numeric(5,2) default 0
);

-- RLS
alter table public.profiles enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'user_select_own_profile'
  ) then
    execute 'create policy user_select_own_profile on public.profiles for select using (user_id = auth.uid())';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'user_update_own_profile'
  ) then
    execute 'create policy user_update_own_profile on public.profiles for update using (user_id = auth.uid()) with check (user_id = auth.uid())';
  end if;
end $$;

-- Helper to create tenant-can policies
do $$
declare
  t text;
  pname text;
begin
  -- Tables must have a tenant_id column; exclude kit_items (no tenant_id)
  foreach t in array array['customers','leads','jobs','proposals','items','kits','invoices','payments','documents','tasks','service_tickets','background_jobs','settings'] loop
    execute format('alter table public.%I enable row level security;', t);

    -- SELECT policy
    pname := format('tenant_can_select_%s', t);
    if not exists (
      select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = pname
    ) then
      execute format(
        'create policy %I on public.%I for select using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))',
        pname, t
      );
    end if;

    -- INSERT policy
    pname := format('tenant_can_insert_%s', t);
    if not exists (
      select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = pname
    ) then
      execute format(
        'create policy %I on public.%I for insert with check (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))',
        pname, t
      );
    end if;

    -- UPDATE policy
    pname := format('tenant_can_update_%s', t);
    if not exists (
      select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = pname
    ) then
      execute format(
        'create policy %I on public.%I for update using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))',
        pname, t
      );
    end if;

    -- DELETE policy
    pname := format('tenant_can_delete_%s', t);
    if not exists (
      select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = pname
    ) then
      execute format(
        'create policy %I on public.%I for delete using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))',
        pname, t
      );
    end if;
  end loop;
end $$;

alter table public.tenants enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'tenants' and policyname = 'tenant_can_select_tenants'
  ) then
    execute 'create policy tenant_can_select_tenants on public.tenants for select using (id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'tenants' and policyname = 'tenant_can_update_tenants'
  ) then
    execute 'create policy tenant_can_update_tenants on public.tenants for update using (id = (select tenant_id from public.profiles where user_id = auth.uid())) with check (id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
end $$;

-- Storage bucket and policies
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

-- Storage RLS policies (idempotent via DROP IF EXISTS)
drop policy if exists tenant_read_own_documents on storage.objects;
create policy tenant_read_own_documents on storage.objects for select
  using (bucket_id = 'documents' and name like ((select tenant_id::text from public.profiles where user_id = auth.uid()) || '/%'));

drop policy if exists tenant_write_own_documents on storage.objects;
create policy tenant_write_own_documents on storage.objects for insert to authenticated
  with check (bucket_id = 'documents' and name like ((select tenant_id::text from public.profiles where user_id = auth.uid()) || '/%'));

drop policy if exists tenant_update_own_documents on storage.objects;
create policy tenant_update_own_documents on storage.objects for update
  using (bucket_id = 'documents' and name like ((select tenant_id::text from public.profiles where user_id = auth.uid()) || '/%'));

drop policy if exists tenant_delete_own_documents on storage.objects;
create policy tenant_delete_own_documents on storage.objects for delete
  using (bucket_id = 'documents' and name like ((select tenant_id::text from public.profiles where user_id = auth.uid()) || '/%'));

-- <<< 0001_init.sql <<<


-- >>> 0002_add_proposals_lang.sql >>>
-- Add language column to proposals for EN/ML PDFs
alter table if exists public.proposals
  add column if not exists lang text default 'en';


-- <<< 0002_add_proposals_lang.sql <<<


-- >>> 0002_owner_policies.sql >>>
-- Enforce owner-only writes on items, kits, and settings (idempotent)

-- ITEMS
do $$
begin
  if exists (
    select 1 from pg_policies where schemaname='public' and tablename='items' and policyname='tenant_can_insert_items'
  ) then
    execute 'drop policy tenant_can_insert_items on public.items';
  end if;
  if exists (
    select 1 from pg_policies where schemaname='public' and tablename='items' and policyname='tenant_can_update_items'
  ) then
    execute 'drop policy tenant_can_update_items on public.items';
  end if;
  if exists (
    select 1 from pg_policies where schemaname='public' and tablename='items' and policyname='tenant_can_delete_items'
  ) then
    execute 'drop policy tenant_can_delete_items on public.items';
  end if;

  execute 'create policy owner_can_insert_items on public.items for insert
    with check (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
      and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = items.tenant_id and p.role = ''owner'')
    )';

  execute 'create policy owner_can_update_items on public.items for update using (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
      and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = items.tenant_id and p.role = ''owner'')
    )';

  execute 'create policy owner_can_delete_items on public.items for delete using (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
      and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = items.tenant_id and p.role = ''owner'')
    )';
end $$;

-- KITS
do $$
begin
  if exists (select 1 from pg_policies where schemaname='public' and tablename='kits' and policyname='tenant_can_insert_kits') then
    execute 'drop policy tenant_can_insert_kits on public.kits';
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='kits' and policyname='tenant_can_update_kits') then
    execute 'drop policy tenant_can_update_kits on public.kits';
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='kits' and policyname='tenant_can_delete_kits') then
    execute 'drop policy tenant_can_delete_kits on public.kits';
  end if;

  execute 'create policy owner_can_insert_kits on public.kits for insert with check (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = kits.tenant_id and p.role = ''owner'')
  )';
  execute 'create policy owner_can_update_kits on public.kits for update using (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = kits.tenant_id and p.role = ''owner'')
  )';
  execute 'create policy owner_can_delete_kits on public.kits for delete using (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = kits.tenant_id and p.role = ''owner'')
  )';
end $$;

-- SETTINGS
do $$
begin
  if exists (select 1 from pg_policies where schemaname='public' and tablename='settings' and policyname='tenant_can_insert_settings') then
    execute 'drop policy tenant_can_insert_settings on public.settings';
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='settings' and policyname='tenant_can_update_settings') then
    execute 'drop policy tenant_can_update_settings on public.settings';
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='settings' and policyname='tenant_can_delete_settings') then
    execute 'drop policy tenant_can_delete_settings on public.settings';
  end if;

  execute 'create policy owner_can_insert_settings on public.settings for insert with check (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = settings.tenant_id and p.role = ''owner'')
  )';
  execute 'create policy owner_can_update_settings on public.settings for update using (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = settings.tenant_id and p.role = ''owner'')
  )';
  execute 'create policy owner_can_delete_settings on public.settings for delete using (
    tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()) and exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.tenant_id = settings.tenant_id and p.role = ''owner'')
  )';
end $$;

-- <<< 0002_owner_policies.sql <<<


-- >>> 0002_profiles_rls_extend.sql >>>
-- Extend profiles RLS: allow tenant users to SELECT team directory, and admins to UPDATE member details.
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'tenant_can_select_profiles'
  ) then
    execute 'create policy tenant_can_select_profiles on public.profiles for select using (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
    )';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'admin_can_update_profiles'
  ) then
    execute 'create policy admin_can_update_profiles on public.profiles for update using (
      exists (
        select 1 from public.profiles me
        where me.user_id = auth.uid()
          and me.tenant_id = profiles.tenant_id
          and me.role in (''owner'',''admin'')
      )
    ) with check (
      exists (
        select 1 from public.profiles me
        where me.user_id = auth.uid()
          and me.tenant_id = profiles.tenant_id
          and me.role in (''owner'',''admin'')
      )
    )';
  end if;
end $$;


-- <<< 0002_profiles_rls_extend.sql <<<


-- >>> 0003_profiles_rls_fix.sql >>>
-- Fix RLS recursion on profiles by using SECURITY DEFINER helper functions.
-- Creates stable helpers to fetch current tenant id and admin status without RLS recursion.

create or replace function public.app_current_tenant_id()
returns uuid
language sql
security definer
set search_path = public
as $$
  select tenant_id from public.profiles where user_id = auth.uid() limit 1
$$;

create or replace function public.app_is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid()
      and role in ('owner','admin')
  )
$$;

revoke all on function public.app_current_tenant_id() from public;
revoke all on function public.app_is_admin() from public;
grant execute on function public.app_current_tenant_id() to anon, authenticated;
grant execute on function public.app_is_admin() to anon, authenticated;

do $$
begin
  -- Replace tenant_can_select_profiles policy using function to avoid recursion
  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'tenant_can_select_profiles'
  ) then
    execute 'drop policy tenant_can_select_profiles on public.profiles';
  end if;
  execute 'create policy tenant_can_select_profiles on public.profiles for select using (
    tenant_id = public.app_current_tenant_id()
  )';

  -- Replace admin_can_update_profiles policy similarly
  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'admin_can_update_profiles'
  ) then
    execute 'drop policy admin_can_update_profiles on public.profiles';
  end if;
  execute 'create policy admin_can_update_profiles on public.profiles for update using (
    public.app_is_admin() and tenant_id = public.app_current_tenant_id()
  ) with check (
    public.app_is_admin() and tenant_id = public.app_current_tenant_id()
  )';
end $$;


-- <<< 0003_profiles_rls_fix.sql <<<


-- >>> 0003_settings_company.sql >>>
-- Extend settings with company profile fields (idempotent)
alter table public.settings add column if not exists company_phone text;
alter table public.settings add column if not exists company_email text;
alter table public.settings add column if not exists company_address text;
alter table public.settings add column if not exists company_logo_url text;


-- <<< 0003_settings_company.sql <<<


-- >>> 0004_profiles_owner_manage.sql >>>
-- Use simple drop-if-exists + create to avoid DO/EXECUTE quoting issues on Supabase
drop policy if exists owner_can_select_profiles on public.profiles;
drop policy if exists owner_can_update_profiles on public.profiles;

create policy owner_can_select_profiles on public.profiles
for select
using (
  tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
  and exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.tenant_id = profiles.tenant_id
      and p.role = 'owner'
  )
);

create policy owner_can_update_profiles on public.profiles
for update
using (
  tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
  and exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.tenant_id = profiles.tenant_id
      and p.role = 'owner'
  )
)
with check (
  tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
  and exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.tenant_id = profiles.tenant_id
      and p.role = 'owner'
  )
);

-- <<< 0004_profiles_owner_manage.sql <<<


-- >>> 0005_profiles_owner_fn_and_policies.sql >>>
-- Create helper function to check owner role without triggering RLS recursion
create or replace function public.is_owner_of_tenant(target_tenant uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid()
      and p.tenant_id = target_tenant
      and p.role = 'owner'
  );
$$;

revoke all on function public.is_owner_of_tenant(uuid) from public;
grant execute on function public.is_owner_of_tenant(uuid) to authenticated;

-- Recreate profiles policies to use the function (avoids self-referential recursion)
drop policy if exists owner_can_select_profiles on public.profiles;
drop policy if exists owner_can_update_profiles on public.profiles;

create policy owner_can_select_profiles on public.profiles
for select using (
  public.is_owner_of_tenant(tenant_id)
);

create policy owner_can_update_profiles on public.profiles
for update using (
  public.is_owner_of_tenant(tenant_id)
) with check (
  public.is_owner_of_tenant(tenant_id)
);


-- <<< 0005_profiles_owner_fn_and_policies.sql <<<


-- >>> 0006_indexes.sql >>>
-- Common indexes to improve performance on frequently filtered columns
-- Idempotent: use IF NOT EXISTS to avoid errors on re-apply

-- Tenant-scoped tables
create index if not exists idx_customers_tenant on public.customers(tenant_id);
create index if not exists idx_leads_tenant on public.leads(tenant_id);
create index if not exists idx_jobs_tenant on public.jobs(tenant_id);
create index if not exists idx_proposals_tenant on public.proposals(tenant_id);
create index if not exists idx_items_tenant on public.items(tenant_id);
create index if not exists idx_kits_tenant on public.kits(tenant_id);
create index if not exists idx_invoices_tenant on public.invoices(tenant_id);
create index if not exists idx_payments_tenant on public.payments(tenant_id);
create index if not exists idx_documents_tenant on public.documents(tenant_id);
create index if not exists idx_tasks_tenant on public.tasks(tenant_id);
create index if not exists idx_service_tickets_tenant on public.service_tickets(tenant_id);
create index if not exists idx_background_jobs_tenant on public.background_jobs(tenant_id);
create index if not exists idx_settings_tenant on public.settings(tenant_id);

-- Foreign key and status/date filters
create index if not exists idx_jobs_customer on public.jobs(customer_id);
create index if not exists idx_jobs_status on public.jobs(status);

create index if not exists idx_invoices_job on public.invoices(job_id);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_due_date on public.invoices(due_date);

create index if not exists idx_payments_invoice on public.payments(invoice_id);

create index if not exists idx_proposals_job on public.proposals(job_id);
create index if not exists idx_proposals_date on public.proposals(date);

create index if not exists idx_documents_job on public.documents(job_id);

create index if not exists idx_tasks_job on public.tasks(job_id);
create index if not exists idx_tasks_status on public.tasks(status);

create index if not exists idx_service_tickets_customer on public.service_tickets(customer_id);
create index if not exists idx_service_tickets_job on public.service_tickets(job_id);
create index if not exists idx_service_tickets_status on public.service_tickets(status);

create index if not exists idx_leads_assigned_to on public.leads(assigned_to);
create index if not exists idx_leads_status on public.leads(status);
create index if not exists idx_leads_date on public.leads(date);

create index if not exists idx_background_jobs_type on public.background_jobs(type);
create index if not exists idx_background_jobs_run_at on public.background_jobs(run_at);


-- <<< 0006_indexes.sql <<<


-- >>> 0007_audit_logs.sql >>>
-- Audit logs table and basic RLS policies

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid,
  action text not null,
  entity text,
  entity_id text,
  metadata jsonb,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_audit_tenant on public.audit_logs(tenant_id);
create index if not exists idx_audit_action on public.audit_logs(action);
create index if not exists idx_audit_created_at on public.audit_logs(created_at);

-- Enable RLS and allow tenant-scoped access
alter table public.audit_logs enable row level security;

-- Idempotent policy creation for select/insert
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='audit_logs' and policyname='tenant_can_select_audit_logs'
  ) then
    execute 'create policy tenant_can_select_audit_logs on public.audit_logs for select using (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
    )';
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='audit_logs' and policyname='tenant_can_insert_audit_logs'
  ) then
    execute 'create policy tenant_can_insert_audit_logs on public.audit_logs for insert with check (
      tenant_id = (select tenant_id from public.profiles where user_id = auth.uid())
    )';
  end if;
end $$;


-- <<< 0007_audit_logs.sql <<<


-- >>> 0007_proposal_extras.sql >>>
-- Persist optional cover/notes/work schedule on proposals
alter table if exists public.proposals
  add column if not exists cover jsonb,
  add column if not exists notes jsonb,
  add column if not exists work_schedule jsonb;


-- <<< 0007_proposal_extras.sql <<<


-- >>> 0008_audit_triggers.sql >>>
-- Audit triggers for sensitive tables: invoices, payments, documents

create or replace function public.audit_log_change() returns trigger as $$
declare
  acting_user uuid;
  action_text text;
  entity_text text;
  entity_id_text text;
  payload jsonb;
begin
  -- who
  begin
    acting_user := auth.uid();
  exception when others then
    acting_user := null;
  end;

  -- what
  if tg_op = 'INSERT' then
    action_text := lower(tg_table_name) || '.insert';
    entity_text := tg_table_name;
    entity_id_text := coalesce(new.id::text, coalesce(new.invoice_id::text, new.job_id::text));
    payload := to_jsonb(new);
    insert into public.audit_logs(tenant_id, user_id, action, entity, entity_id, metadata)
      values (new.tenant_id, acting_user, action_text, entity_text, entity_id_text, payload);
    return new;
  elsif tg_op = 'DELETE' then
    action_text := lower(tg_table_name) || '.delete';
    entity_text := tg_table_name;
    entity_id_text := coalesce(old.id::text, coalesce(old.invoice_id::text, old.job_id::text));
    payload := to_jsonb(old);
    insert into public.audit_logs(tenant_id, user_id, action, entity, entity_id, metadata)
      values (old.tenant_id, acting_user, action_text, entity_text, entity_id_text, payload);
    return old;
  else
    return new;
  end if;
end;
$$ language plpgsql security definer set search_path = public;

-- Invoices
drop trigger if exists trg_audit_invoices_ins on public.invoices;
create trigger trg_audit_invoices_ins after insert on public.invoices
  for each row execute function public.audit_log_change();

-- Payments
drop trigger if exists trg_audit_payments_ins on public.payments;
create trigger trg_audit_payments_ins after insert on public.payments
  for each row execute function public.audit_log_change();

-- Documents (insert + delete)
drop trigger if exists trg_audit_documents_ins on public.documents;
create trigger trg_audit_documents_ins after insert on public.documents
  for each row execute function public.audit_log_change();

drop trigger if exists trg_audit_documents_del on public.documents;
create trigger trg_audit_documents_del after delete on public.documents
  for each row execute function public.audit_log_change();


-- <<< 0008_audit_triggers.sql <<<


-- >>> 0009_audit_update_invoices.sql >>>
-- Audit UPDATEs on invoices to capture status/amount changes

create or replace function public.audit_log_invoice_update() returns trigger as $$
declare
  acting_user uuid;
begin
  begin
    acting_user := auth.uid();
  exception when others then
    acting_user := null;
  end;

  if (old.status is distinct from new.status)
     or (old.total is distinct from new.total)
     or (old.due_date is distinct from new.due_date) then
    insert into public.audit_logs(tenant_id, user_id, action, entity, entity_id, metadata)
    values (
      new.tenant_id,
      acting_user,
      'invoices.update',
      'invoices',
      new.id::text,
      jsonb_build_object(
        'old_status', old.status,
        'new_status', new.status,
        'old_total', old.total,
        'new_total', new.total,
        'old_due_date', old.due_date,
        'new_due_date', new.due_date
      )
    );
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists trg_audit_invoices_upd on public.invoices;
create trigger trg_audit_invoices_upd after update on public.invoices
  for each row execute function public.audit_log_invoice_update();


-- <<< 0009_audit_update_invoices.sql <<<


-- >>> 0010_fix_audit_triggers.sql >>>
-- Fix audit trigger function to avoid referencing non-existent columns
-- Previous version used NEW.invoice_id/NEW.job_id which fails on tables without those fields.

create or replace function public.audit_log_change() returns trigger as $$
declare
  acting_user uuid;
  action_text text;
  entity_text text;
  entity_id_text text;
  payload jsonb;
begin
  -- who
  begin
    acting_user := auth.uid();
  exception when others then
    acting_user := null;
  end;

  entity_text := tg_table_name;

  if tg_op = 'INSERT' then
    action_text := lower(tg_table_name) || '.insert';
    payload := to_jsonb(new);
    -- use primary key id where available (all our audited tables have id)
    entity_id_text := coalesce((payload->>'id'), (payload->>'job_id'), (payload->>'invoice_id'));
    insert into public.audit_logs(tenant_id, user_id, action, entity, entity_id, metadata)
      values (new.tenant_id, acting_user, action_text, entity_text, entity_id_text, payload);
    return new;
  elsif tg_op = 'DELETE' then
    action_text := lower(tg_table_name) || '.delete';
    payload := to_jsonb(old);
    entity_id_text := coalesce((payload->>'id'), (payload->>'job_id'), (payload->>'invoice_id'));
    insert into public.audit_logs(tenant_id, user_id, action, entity, entity_id, metadata)
      values (old.tenant_id, acting_user, action_text, entity_text, entity_id_text, payload);
    return old;
  else
    return new;
  end if;
end;
$$ language plpgsql security definer set search_path = public;

-- Recreate triggers to pick up function changes (idempotent)
drop trigger if exists trg_audit_invoices_ins on public.invoices;
create trigger trg_audit_invoices_ins after insert on public.invoices
  for each row execute function public.audit_log_change();

drop trigger if exists trg_audit_payments_ins on public.payments;
create trigger trg_audit_payments_ins after insert on public.payments
  for each row execute function public.audit_log_change();

drop trigger if exists trg_audit_documents_ins on public.documents;
create trigger trg_audit_documents_ins after insert on public.documents
  for each row execute function public.audit_log_change();

drop trigger if exists trg_audit_documents_del on public.documents;
create trigger trg_audit_documents_del after delete on public.documents
  for each row execute function public.audit_log_change();


-- <<< 0010_fix_audit_triggers.sql <<<


-- >>> 0010_program_followup_quotes.sql >>>
-- Add program type enum and column on jobs
do $$ begin
  create type program_type as enum ('PM_Surya', 'Commercial');
exception when duplicate_object then null; end $$;

alter table public.jobs
  add column if not exists program_type program_type default 'PM_Surya'::program_type;

-- Lead follow-up fields
alter table public.leads
  add column if not exists next_follow_up_date date,
  add column if not exists last_contacted_at date;

-- Quote numbering settings
alter table public.settings
  add column if not exists quote_prefix text,
  add column if not exists quote_format text;


-- <<< 0010_program_followup_quotes.sql <<<


-- >>> 0013_branches_and_branch_fk.sql >>>
-- Branches table and branch_id references on leads/jobs

-- Create branches table (idempotent)
create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

-- Enable RLS and basic tenant policies on branches
alter table public.branches enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'branches' and policyname = 'tenant_can_select_branches'
  ) then
    execute 'create policy tenant_can_select_branches on public.branches for select using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'branches' and policyname = 'tenant_can_insert_branches'
  ) then
    execute 'create policy tenant_can_insert_branches on public.branches for insert with check (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'branches' and policyname = 'tenant_can_update_branches'
  ) then
    execute 'create policy tenant_can_update_branches on public.branches for update using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'branches' and policyname = 'tenant_can_delete_branches'
  ) then
    execute 'create policy tenant_can_delete_branches on public.branches for delete using (tenant_id = (select tenant_id from public.profiles where user_id = auth.uid()))';
  end if;
end $$;

-- Add branch_id to leads and jobs (nullable for backward compatibility)
alter table public.leads add column if not exists branch_id uuid;
alter table public.jobs  add column if not exists branch_id uuid;

-- Add FKs if missing (on delete set null)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'leads_branch_fk'
  ) then
    alter table public.leads add constraint leads_branch_fk foreign key (branch_id) references public.branches(id) on delete set null;
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'jobs_branch_fk'
  ) then
    alter table public.jobs add constraint jobs_branch_fk foreign key (branch_id) references public.branches(id) on delete set null;
  end if;
end $$;

-- Helpful indexes
create index if not exists idx_leads_branch on public.leads(branch_id);
create index if not exists idx_jobs_branch on public.jobs(branch_id);


-- <<< 0013_branches_and_branch_fk.sql <<<


-- >>> 0014_soft_delete_archive_and_void.sql >>>
-- Add soft-delete and archive columns (idempotent guards)
do $$
begin
  -- customers.deleted_at
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'customers' and column_name = 'deleted_at'
  ) then
    alter table public.customers add column deleted_at timestamptz;
  end if;

  -- items.archived
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'items' and column_name = 'archived'
  ) then
    alter table public.items add column archived boolean not null default false;
  end if;

  -- proposals.voided_at
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'proposals' and column_name = 'voided_at'
  ) then
    alter table public.proposals add column voided_at timestamptz;
  end if;
end $$;


-- <<< 0014_soft_delete_archive_and_void.sql <<<


-- >>> 0015_adminish_rls.sql >>>
-- Broaden owner-only policies to allow Admin as well (adminish).
-- Replaces owner_can_* policies on items, kits, and settings with admin_can_* using
-- public.app_current_tenant_id() and public.app_is_admin() helpers (SECURITY DEFINER).

do $$
begin
  -- ITEMS
  execute 'drop policy if exists owner_can_insert_items on public.items';
  execute 'drop policy if exists owner_can_update_items on public.items';
  execute 'drop policy if exists owner_can_delete_items on public.items';
  execute 'drop policy if exists admin_can_insert_items on public.items';
  execute 'drop policy if exists admin_can_update_items on public.items';
  execute 'drop policy if exists admin_can_delete_items on public.items';

  execute 'create policy admin_can_insert_items on public.items for insert with check (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_update_items on public.items for update using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_delete_items on public.items for delete using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';

  -- KITS
  execute 'drop policy if exists owner_can_insert_kits on public.kits';
  execute 'drop policy if exists owner_can_update_kits on public.kits';
  execute 'drop policy if exists owner_can_delete_kits on public.kits';
  execute 'drop policy if exists admin_can_insert_kits on public.kits';
  execute 'drop policy if exists admin_can_update_kits on public.kits';
  execute 'drop policy if exists admin_can_delete_kits on public.kits';

  execute 'create policy admin_can_insert_kits on public.kits for insert with check (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_update_kits on public.kits for update using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_delete_kits on public.kits for delete using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';

  -- SETTINGS
  execute 'drop policy if exists owner_can_insert_settings on public.settings';
  execute 'drop policy if exists owner_can_update_settings on public.settings';
  execute 'drop policy if exists owner_can_delete_settings on public.settings';
  execute 'drop policy if exists admin_can_insert_settings on public.settings';
  execute 'drop policy if exists admin_can_update_settings on public.settings';
  execute 'drop policy if exists admin_can_delete_settings on public.settings';

  execute 'create policy admin_can_insert_settings on public.settings for insert with check (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_update_settings on public.settings for update using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
  execute 'create policy admin_can_delete_settings on public.settings for delete using (
    tenant_id = public.app_current_tenant_id() and public.app_is_admin()
  )';
end $$;


-- <<< 0015_adminish_rls.sql <<<


-- >>> 0016_bootstrap_profile_on_signup.sql >>>
-- Auto-provision tenant + profile for new auth users to avoid "Profile not ready" UX.
-- Idempotent: recreate function and trigger safely.

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_tenant uuid;
  v_name text;
begin
  -- If a profile already exists for this user, do nothing
  if exists (select 1 from public.profiles where user_id = new.id) then
    return new;
  end if;

  -- Derive a friendly name from email if available
  v_name := coalesce(new.raw_user_meta_data->>'name', new.email, 'User');

  -- Create a tenant and owner profile for this user
  insert into public.tenants(name) values (coalesce(v_name, 'Company'))
    returning id into v_tenant;

  insert into public.profiles(user_id, tenant_id, role, display_name)
    values (new.id, v_tenant, 'owner', v_name);

  -- Seed default settings for the new tenant if not present
  insert into public.settings(tenant_id, currency, default_tax_rate, deposit_percent)
    values (v_tenant, 'INR', 0, 0)
    on conflict do nothing;

  return new;
end;
$$;

-- Create trigger on auth.users to call the bootstrapper
drop trigger if exists trg_handle_new_auth_user on auth.users;
create trigger trg_handle_new_auth_user
  after insert on auth.users
  for each row
  execute function public.handle_new_auth_user();

-- Hardening: prevent direct execution; only the trigger should invoke this.
revoke all on function public.handle_new_auth_user() from public;
revoke all on function public.handle_new_auth_user() from anon;
revoke all on function public.handle_new_auth_user() from authenticated;

-- <<< 0016_bootstrap_profile_on_signup.sql <<<


-- >>> 0017_bootstrap_only_first_user.sql >>>
-- Modify bootstrap to only auto-provision for the first-ever user/tenant.
-- Prevents accidental tenant sprawl when normal team members sign in with Gmail.

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_tenant uuid;
  v_name text;
  v_has_any boolean;
begin
  -- If a profile already exists for this user, do nothing
  if exists (select 1 from public.profiles where user_id = new.id) then
    return new;
  end if;

  -- Only bootstrap when there are no tenants yet (first user wins)
  select exists(select 1 from public.tenants) into v_has_any;
  if v_has_any then
    -- Do not auto-create a tenant; wait for admin invite to assign profile
    return new;
  end if;

  v_name := coalesce(new.raw_user_meta_data->>'name', new.email, 'Owner');
  insert into public.tenants(name) values (coalesce(v_name, 'Company'))
    returning id into v_tenant;
  insert into public.profiles(user_id, tenant_id, role, display_name)
    values (new.id, v_tenant, 'owner', v_name);
  insert into public.settings(tenant_id, currency, default_tax_rate, deposit_percent)
    values (v_tenant, 'INR', 0, 0)
    on conflict do nothing;
  return new;
end;
$$;


-- <<< 0017_bootstrap_only_first_user.sql <<<


-- >>> 0018_role_enum_extend.sql >>>
-- Ensure the role enum contains all app roles used by the UI.
-- Safe, idempotent adds per label.
do $$ begin
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'admin'
  ) then
    alter type role add value 'admin';
  end if;
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'manager'
  ) then
    alter type role add value 'manager';
  end if;
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'sales'
  ) then
    alter type role add value 'sales';
  end if;
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'technician'
  ) then
    alter type role add value 'technician';
  end if;
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'accountant'
  ) then
    alter type role add value 'accountant';
  end if;
  if not exists (
    select 1 from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    where t.typname = 'role' and e.enumlabel = 'viewer'
  ) then
    alter type role add value 'viewer';
  end if;
  -- 'staff' already exists in initial enum; keep for backward compatibility.
end $$;


-- <<< 0018_role_enum_extend.sql <<<


-- >>> 0019_unique_constraints_and_indexes.sql >>>
-- Add high-value unique constraints and indexes (idempotent).

-- Customers: avoid duplicate phone within a tenant (when phone is present)
create unique index if not exists idx_customers_tenant_phone_unique
  on public.customers(tenant_id, phone) where phone is not null;

-- Items: unique item_code per tenant
create unique index if not exists idx_items_tenant_item_code_unique
  on public.items(tenant_id, item_code);

-- Kits: unique kit_name per tenant
create unique index if not exists idx_kits_tenant_name_unique
  on public.kits(tenant_id, kit_name);

-- Branches: unique name per tenant
create unique index if not exists idx_branches_tenant_name_unique
  on public.branches(tenant_id, name);

-- Leads: accelerate follow-up filters and status queries
create index if not exists idx_leads_next_follow_up
  on public.leads(next_follow_up_date);

-- Jobs: status filter
create index if not exists idx_jobs_status
  on public.jobs(status);

-- Invoices: due-date filter and job lookup
create index if not exists idx_invoices_due_date
  on public.invoices(due_date);
create index if not exists idx_invoices_job
  on public.invoices(job_id);

-- Payments: invoice join
create index if not exists idx_payments_invoice
  on public.payments(invoice_id);


-- <<< 0019_unique_constraints_and_indexes.sql <<<


-- >>> 0020_fk_assigned_to.sql >>>
-- Add a foreign key for leads.assigned_to to profiles(user_id), nullable.
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public' and table_name = 'leads' and constraint_name = 'leads_assigned_to_fkey'
  ) then
    alter table public.leads
      add constraint leads_assigned_to_fkey
      foreign key (assigned_to)
      references public.profiles(user_id)
      on delete set null;
  end if;
end $$;


-- <<< 0020_fk_assigned_to.sql <<<


-- >>> 0021_customers_soft_delete_rls.sql >>>
-- Exclude soft-deleted customers from normal SELECT via RLS.
do $$
begin
  -- Drop generic tenant select policy if present
  if exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'customers' and policyname = 'tenant_can_select_customers'
  ) then
    execute 'drop policy tenant_can_select_customers on public.customers';
  end if;
  -- Create refined policy that omits deleted rows
  execute 'create policy tenant_can_select_customers on public.customers for select using (
    tenant_id = public.app_current_tenant_id() and deleted_at is null
  )';
end $$;


-- <<< 0021_customers_soft_delete_rls.sql <<<


-- >>> 0022_enforce_last_owner_guard.sql >>>
-- Prevent removing the last owner of a tenant.
create or replace function public.enforce_at_least_one_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant uuid;
  v_remaining integer;
begin
  if TG_OP = 'DELETE' then
    v_tenant := old.tenant_id;
    if old.role = 'owner' then
      select count(*) into v_remaining from public.profiles
      where tenant_id = v_tenant and user_id <> old.user_id and role = 'owner';
      if coalesce(v_remaining,0) = 0 then
        raise exception 'Cannot remove the last owner from tenant %', v_tenant;
      end if;
    end if;
    return old;
  elsif TG_OP = 'UPDATE' then
    v_tenant := new.tenant_id;
    if old.role = 'owner' and new.role <> 'owner' then
      select count(*) into v_remaining from public.profiles
      where tenant_id = v_tenant and user_id <> old.user_id and role = 'owner';
      if coalesce(v_remaining,0) = 0 then
        raise exception 'Tenant % must retain at least one owner', v_tenant;
      end if;
    end if;
    return new;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_last_owner on public.profiles;
create trigger trg_enforce_last_owner
before update or delete on public.profiles
for each row execute function public.enforce_at_least_one_owner();


-- <<< 0022_enforce_last_owner_guard.sql <<<

COMMIT;
