import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

function main() {
  const root = process.cwd();
  const drizzleDir = join(root, 'drizzle');
  const outDir = join(root, 'supabase');
  const outFile = join(outDir, 'bootstrap_all.sql');

  try { mkdirSync(outDir, { recursive: true }); } catch {}

  const all = readdirSync(drizzleDir)
    .filter((f) => f.endsWith('.sql'));
  // Ensure enum extension that adds 'admin' lands before any policy using it
  const first: string[] = [];
  const rest: string[] = [];
  for (const f of all) {
    if (f.includes('role_enum_extend')) first.push(f);
    else if (f.startsWith('0001_')) first.unshift(f); // keep 0001 at the very start
    else rest.push(f);
  }
  const files = [...first, ...rest].sort((a, b) => a.localeCompare(b));
  if (files.length === 0) {
    console.error('No SQL files found under drizzle/.');
    process.exit(1);
  }

  const header = `-- Auto-generated by scripts/bootstrap-db.ts\n-- Concatenated migrations from drizzle/ in lexical order.\n-- You can apply this with:\n--   npx supabase db reset\n--   npx supabase db query -f supabase/bootstrap_all.sql\n\nBEGIN;\n`;
  const footer = `\nCOMMIT;\n`;

  const body = files
    .map((f) => {
      const p = join(drizzleDir, f);
      return `\n-- >>> ${f} >>>\n` + readFileSync(p, 'utf8') + `\n-- <<< ${f} <<<\n`;
    })
    .join('\n');

  writeFileSync(outFile, header + body + footer, 'utf8');
  console.log(`Wrote ${outFile}`);
  console.log('\nNext run:');
  console.log('  npx supabase link --project-ref <your-project-ref>');
  console.log('  npx supabase db reset');
  console.log('  npx supabase db query -f supabase/bootstrap_all.sql');
}

main();
